server:
  port: 8080

spring:
  application:
    name: ubc-planner
  profiles:
    default: local
  datasource:
    url: jdbc:postgresql://localhost:5432/ubcplanner
    username: ubc
    password: ubc
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
