spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ubcplanner
    username: ubc
    password: ubc
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: warn
