spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ubcplanner
    username: ubc
    password: ubc

  jpa:
    hibernate:
      ddl-auto: update  # dev only
    properties:
      hibernate.jdbc.time_zone: UTC

logging:
  level:
    org.hibernate.SQL: warn

ubc:
  exams:
    searchUrl: "https://students.ubc.ca/enrolment/exams/exam-schedule"

